"""empty message

Revision ID: 109f6d4cf256
Revises: d56f88685c8b
Create Date: 2022-06-25 19:06:33.675282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '109f6d4cf256'
down_revision = 'd56f88685c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=64), nullable=True))
    op.drop_index('ix_user_username', table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
